update CHS translation to the latest build
MysticMods/Traverse pull request #35
Opened 2021-01-02 01:47 UTC by TUsama

2021-01-02 01:53 UTC, TUsama commented
@noobanidus sorry for this late PR, actually, I finished it yesterday, but I forgot to open this PR...

2021-01-02 01:53 UTC, TUsama commented
@WuzgXY-GitHub

2021-01-02 03:46 UTC, WuzgXY-GitHub requested changes
[References](https://minecraft-zh.gamepedia.com/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96)

「重铸」是不是可以换一换？这毕竟不是整金属的模组，重铸不合适吧

2021-01-02 03:46 UTC, WuzgXY-GitHub commented on src/main/resources/assets/traverse/lang/zh_cn.json
> +	"biome.traverse.coniferous_woodland_hills_biome":"冷杉林山",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
	"biome.traverse.coniferous_woodland_hills_biome":"冷杉林丘陵",
```

2021-01-02 03:46 UTC, WuzgXY-GitHub commented on src/main/resources/assets/traverse/lang/zh_cn.json
> +	"biome.traverse.snowy_coniferous_wooded_hills":"积雪的冷杉林山脉",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
	"biome.traverse.snowy_coniferous_wooded_hills":"积雪的冷杉林丘陵",
```

Mountains 才是「山地」

Hills 一词在[沼泽变种](https://minecraft-zh.gamepedia.com/%E6%B2%BC%E6%B3%BD#.E6.B2.BC.E6.B3.BD.E5.B1.B1.E4.B8.98)处被翻译为「山丘」，但可能是翻译错误，建议联系广药或 ff。其它译名中都是「丘陵」。

2021-01-02 03:46 UTC, WuzgXY-GitHub commented on src/main/resources/assets/traverse/lang/zh_cn.json
>  	"biome.traverse.autumnal_wooded_hills":"秋木山脉",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|
```suggestion
	"biome.traverse.autumnal_wooded_hills":"秋木丘陵",
```
同下。

2021-01-02 03:46 UTC, WuzgXY-GitHub commented on src/main/resources/assets/traverse/lang/zh_cn.json
>  	"biome.traverse.meadow":"牧场",
|Feedback Priority|
|---|
|🧗‍♀️ Boulder / **Blocking**|

```suggestion
	"biome.traverse.meadow":"草地",
```

2021-01-02 03:46 UTC, WuzgXY-GitHub commented on src/main/resources/assets/traverse/lang/zh_cn.json
>  	"biome.traverse.plains_plateau":"高地平原",
|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

Plateau 译为「高原」更符合统一标准，但这样略显生硬，请自行定夺。

2021-01-02 04:35 UTC, TUsama commented on src/main/resources/assets/traverse/lang/zh_cn.json
>  	"biome.traverse.autumnal_wooded_hills":"秋木山脉",
秋森丘陵比较好。

2021-01-02 04:37 UTC, TUsama commented on src/main/resources/assets/traverse/lang/zh_cn.json
>  	"biome.traverse.plains_plateau":"高地平原",
> 高原（Plateau）是指海拔高度在500米以上的地区，地势相对平坦或者有一定起伏的广阔地区。
有的高原表面宽广平坦，地势起伏不大；有的高原则是山峦起伏，地势变化很大。

只译成高原略微不妥。

2021-01-02 22:10 UTC, noobanidus commented
Hi TUsama & the rest of your group -- I just realised Litwordhoek existed. I just wanted to double check if this is ready to be merged?

2021-01-02 22:16 UTC, merged

2021-01-02 22:16 UTC, noobanidus commented
I'll merge this now for the next release. If there are issues, please feel free to open a new patch!

2021-01-03 01:18 UTC, WuzgXY-GitHub commented on src/main/resources/assets/traverse/lang/zh_cn.json
>  	"biome.traverse.plains_plateau":"高地平原",
|Feedback Priority|
|---|
|⛰ Mountain / **Blocking and requires immediate action**|

|Feedback Priority|
|---|
|⚪️ Pebble / Non-blocking but requires future action|

Plateau 译为「高原」更符合统一标准，但这样略显生硬，请自行定夺。